# CARLA Simulation Configuration
simulation:
  carla_host: "localhost"
  carla_port: 2000
  timeout: 10.0
  sync_mode: true
  fixed_delta_seconds: 0.02  # 50Hz simulation
  
world:
  town: "Town02"  # Town01, Town02, Town03
  weather:
    cloudiness: 10.0
    precipitation: 0.0
    sun_altitude_angle: 45.0
    fog_density: 0.0
  
vehicle:
  blueprint: "vehicle.tesla.model3"
  spawn_point:
    x: 107.0
    y: 133.0
    z: 0.5
    yaw: 0.0
  autopilot: false
  
sensors:
  camera:
    width: 84
    height: 84
    fov: 90.0
    location: [2.0, 0.0, 1.4]  # [x, y, z] relative to vehicle
    rotation: [0.0, 0.0, 0.0]  # [pitch, yaw, roll]
    sensor_tick: 0.1  # 10Hz
  
  imu:
    location: [0.0, 0.0, 0.0]
    rotation: [0.0, 0.0, 0.0] 
    sensor_tick: 0.02  # 50Hz
    
  collision:
    location: [0.0, 0.0, 0.0]
    
  lane_invasion:
    location: [0.0, 0.0, 0.0]

traffic:
  num_vehicles: 20
  num_pedestrians: 10
  vehicle_spawn_radius: 100.0
  pedestrian_spawn_radius: 50.0

communication:
  zmq_port: 5555
  zmq_bind_address: "tcp://*:5555"
  zmq_connect_address: "tcp://localhost:5555"
  message_rate_hz: 20

# Deterministic settings for reproducibility
random_seed: 42
numpy_seed: 42
